### ISSUE TITLE
IDEA hangs on Obtaining AWS credentials progress modal without MFA prompt; entire IDE freeze

### ISSUE THREAD

**Issue by DiskImage** [coderazzi/aws_codeartifact_maven#1]
My team recently discovered this plugin and about very few of us have managed to actually get it working. The verbage of the instructions appears to differ a little form AWS' guide's, and we had to change our credential format up because we use roles to grant access to things, rather than just accounts, and this plugin seems role unaware. However, the main issue I'm facing is that when I match the inputs and credentials file that my teammate that succeeded in setup used, mine doesn't work. 

Expected: Fill in the generate modal information and click generate to continue, get prompted for MFA & provide that, then it should move on to obtaining the credentials.

Actual: Fill in the generate modal information and click generate to continue, MFA gets ignored entirely, the "Obtaining AWS credentials" progress modal appears but hangs and does nothing. Clicking cancel causes the button to disable and nothing else to happen. Entire IDE unresponsive due to modal focus, but not listed as "Not responding" in the force quit menu, though force quit is required as regular CMD+Q is ignored. No token generated, still unable to refresh maven.

OS: MacOs Big Sur 11.4 (20F71)
IDE: CE 2021.2

**Comment by coderazzi** [comment]
Hi, Ian, apologies for the very late reply, I have been totally offline for
almost one month.

I created the plugin for my own team, and we are using just accounts, so,
you are right, it is role agnostic. And we are not using MFA.
In any case, I see in the code where this can be hanging.

I will setup MFA in one account to check this behavior, but I believe the
issue that perhaps you are having relates to how AWS is configured.

To get the codeartifact token, you call:

        aws codeartifact get-authorization-token --domain my_domain
--domain-owner 111122223333 --query authorizationToken --output text

Which, as you see, does not require any login credentials. This assumes
that AWS command line is already setup and properly configured (aws
configure).  Is this your case?

Best regards,

 Luis

**Comment by coderazzi** [comment]
Hi, Ian,

I have created an account with MFA, the behavior is still correct. I would
say that using a role is going to work also fine, so far as you have
invoked correctly aws configure.

But the code was definitely missing the management of the cancel button,
and it should work now fine. I have updated a new version to the
marketplace (1.1.0), but is pending Idea approval,

Best regards,

  Luis
