### ISSUE TITLE
Enhancement: add --no-verify-ssl arge into cli command

### ISSUE THREAD

**Issue by Happy-ArthurYang** [coderazzi/aws_codeartifact_maven#13]
Since the fireware setting in my office/vpn I must use --no-verify-ssl to call aws cli, so does it possible to add this option into the plug?

**Comment by coderazzi** [comment]
Hi,

A quick solution would be creating a aws-wrapper script, that calls the
original AWS script and adds that specific option.

Then you could set the plugin to invoke  this wrapper script.

Would that work for you?

Best,
 Lu

**Comment by Happy-ArthurYang** [comment]
Then how can I set the plugin to invoke the wrapper script? I did not find the place to set it

**Comment by coderazzi** [comment]
Hi,
in the plugin, the last textbox allows you to enter a different PATH
location for the AWS script, just point this location to your script and
you should be golden,
Best,
 Lu.

**Comment by Happy-ArthurYang** [comment]
And the next question is how to ref in input value from the plugin UI. e.g. the Domain, Domain Owner, profile name and Region, if use env, what is the env name should I use?
![image](https://github.com/coderazzi/aws_codeartifact_maven/assets/113080404/4320b320-158a-4179-b98e-ee7515f61d42)
****

**Comment by coderazzi** [comment]
Hi, I am not sure if I fully understand your question:

When you invoke the AWS script, you only need the domain and domain owner,
it will invoked as follows:

aws codeartifact get-authorization-token --domain YOUR-DOMAIN
--domain-owner AS_SPECIFIED --query authorizationToken --output text

And this returns the authorization token provided by AWS.

So, your wrapper script should just do something like (in Linux):

aws --no-verify-ssl $*

or, for windows

aws --no-verify-ssl %*

A limitation of this solution is that the AWS cli path defined in the
plugin is fixed for all profiles, so if you need to add --no-verify-ssl
only for some profiles, you need to make a more complex script, looking for
the --domain parameter.

Does this answer your question?

 L.

**Comment by Happy-ArthurYang** [comment]
This solution works for me. thank you.
