### ISSUE TITLE
Support multiple repos

### ISSUE THREAD

**Issue by martingifted** [coderazzi/aws_codeartifact_maven#3]
Hi! Is there any chance support could be added for multiple repositories? My current use case is that I have separate CodeArtifact repos for releases and for snapshots so I need to swap back and forth.

I would also happily contribute this myself but I am having a lot of trouble setting up a development environment for this plugin using the JetBrains guide for plugin development, do you have any tips?

**Comment by coderazzi** [comment]
Hi, indeed, that seems like a good functionality. I am a bit busy at the
moment, but I will try to have something working here asap,

Best regards,

 Luis

**Comment by coderazzi** [comment]
Hi,
I have uploaded a beta version of the plugin, please give it a try:

https://plugins.jetbrains.com/plugin/16777-aws-codeartifact--maven/versions/beta

Best regards,

 Luis

**Comment by martingifted** [comment]
That is amazing, thank you! But I don't see the beta versions, that link just redirects me to the release versions. I looked around to see if there was something I need to enable but I can't find anything. Maybe its Jetbrains who have to approve the beta release?

Edit: Not sure if it was there before, but I see the beta toggle now :) Sorry!

**Comment by coderazzi** [comment]
Hi,
I guess I sent the link just after upload and indeed JetBrains needed
to enable it: I can see it from other browsers / accounts, so the
link:

https://plugins.jetbrains.com/plugin/16777-aws-codeartifact--maven/versions/beta

should be now working..

Best regards

**Comment by martingifted** [comment]
It works very well, this is super! Thanks a lot coderazzi.

**Comment by coderazzi** [comment]
Ok, I will submit then to the stable channel, thanks for the feedback.
