### ISSUE TITLE
Maven settings file does not define any server whit username 'aws'

### ISSUE THREAD

**Issue by MTurraPpa** [coderazzi/aws_codeartifact_maven#5]
I get this message but my ~/.m2/settings.xml have the server with username aws

```xml
<servers>
  <server>
    <id>myserverid</id>
    <username>aws</username>
    <password>${env.CODEARTIFACT_AUTH_TOKEN}</password>
  </server>
</servers>
```

On MacOs 12.0.1 and IntellyJ 2021.3 (Community Edition)

**Comment by coderazzi** [comment]
Hi, could you send me your settings.xml file?
(overwrite any sensitive information, of course)

Best regards,

 L.

**Comment by MTurraPpa** [comment]
Is the one you see in the issue

Il gio 16 dic 2021, 13:03 coderazzi ***@***.***> ha scritto:

> Hi, could you send me your settings.xml file?
> (overwrite any sensitive information, of course)
>
> Best regards,
>
> L.
>

**Comment by coderazzi** [comment]
Hi, I thought you had only sent the part about the servers.
Your settings.xml is incorrect You need to surround your XML with a
settings element:

<settings>
</settings>

So it will look like:

<settings>
    <servers>
      <server>
        <id>myserverid</id>
        <username>aws</username>
        <password>${env.CODEARTIFACT_AUTH_TOKEN}</password>
      </server>
    </servers>
</settings>

In fact the first line should not be just <settings>, but:

<?xml version="1.0" encoding="UTF-8" standalone="no"?><settings xmlns="
http://maven.apache.org/SETTINGS/1.0.0" xmlns:xsi="
http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="
http://maven.apache.org/SETTINGS/1.0.0
https://maven.apache.org/xsd/settings-1.0.0.xsd">


Best regards,

**Comment by MTurraPpa** [comment]
Right!

Sorry
