### ISSUE TITLE
Request: Ability to specify AWS profile the command is run with

### ISSUE THREAD

**Issue by jagiles-gg** [coderazzi/aws_codeartifact_maven#6]
Based on observation, it appears that the tool runs using either the default profile, or whatever profile is set in the AWS_PROFILE environment variable. 

It would be great if the dialog provided the ability to (optionally) specify a name of the AWS profile to execute the command with. As someone who has access to many AWS accounts and has quite a few in my credentials file, being able to specify which set of credentials the command is executed with would be greatly appreciated.

**Comment by coderazzi** [comment]
Hi, Jason, thanks for the feedback,
you are right, I use the default profile and I hadn't foreseen the need to
include it in the request execution.
I will implement it as soon as possible.

**Comment by jagiles-gg** [comment]
Thank you, sir! Much appreciated.

**Comment by coderazzi** [comment]
Hi, Jason, I have updated the plugin and deployed it on the beta channel:
https://plugins.jetbrains.com/plugin/16777-aws-codeartifact--maven/update/153353

Could you check if it works as you expected?

**Comment by jagiles-gg** [comment]
It does work, but the plugin does assume the existence of a `~/.aws/config` file. If that file does not exist, then an error dialog pops up and the profile drop down is empty. 

You might also fall back to the `~/.aws/credentials` file and read profiles from there? I know when using `aws configure` it puts things in the right place, but the documentation on the CLI does not require that certain properties lie in `~/.aws/config` and does allow for all properties to lie in `~/.aws/credentials`.

I recognize that this is a non-standard setup so feel free to ignore this particular bit of feedback.

**Comment by coderazzi** [comment]
Hi,

yep, that is right. Didn't you have a ~/.aws/config file and got yourself
the error?
Reading the documentation, I understood that both files were required, so
it would make little sense to try reading the credentials file IF the
config file was missing.
I can indeed use the credentials file if the config one is missing, just
not sure if that would help (the config includes the associated region, so
it would be still required).

**Comment by jagiles-gg** [comment]
Yeah...you can probably feel free to ignore. My configuration was setup manually and not through the CLI. So for me, response format, region, etc is all setup in the credentials file. 

I am willing to admit to being in a non-standard setup. If I move those settings to the config file where they are supposed to live I don't see the error.

**Comment by coderazzi** [comment]
Mmmmm... for completeness, I guess I should cover both files :-(

**Comment by coderazzi** [comment]
Hi, Jason,
I uploaded a new beta:
https://plugins.jetbrains.com/plugin/16777-aws-codeartifact--maven/versions/beta/154281
It is now -or it should be- conformant to the AWS specification:
https://docs.aws.amazon.com/sdkref/latest/guide/file-location.html
Please give it a try,
