### ISSUE TITLE
Region support

### ISSUE THREAD

**Issue by bpalermo** [coderazzi/aws_codeartifact_maven#7]
Since CodeArtifact is only available in some regions, would be nice to choose it from the dialog.

**Comment by coderazzi** [comment]
Hi, Bruno, that is a good point, will support it asap.

Best regards,

 L.

**Comment by coderazzi** [comment]
Hi, I have added support for regions in the version 3.1.0-beta (beta channel). 
I have just uploaded it, it should be available in the plugins' page in few hours.
Best,
 L.
