### ISSUE TITLE
Default region not recognized

### ISSUE THREAD

**Issue by raman-blyshchyk-vib** [coderazzi/aws_codeartifact_maven#8]
When try to "Generate credentials" using some custom profile it doesn't recognize that region set in [default] profile from .aws/config file. 
Run "aws configure" doesn't fix issue.
As workaround now can be set env variable AWS_DEFAULT_REGION, but is not very convenient.

**Comment by coderazzi** [comment]
Hi, are you using the default profile to generate the credentials, or other
profile?
I think that if you are using other profile, you need to do first aws
configure --profile XXX
Can you give it a try?
Best

**Comment by raman-blyshchyk-vib** [comment]
Thank you, that worked!
Yes, I was using other than default profile and I completely forgot to add profile to configure command.
Maybe it is a good idea to add such hint to error message, what you think? Maybe it will save someone time :)

**Comment by coderazzi** [comment]
Hi, I can add some check on the error message and suggest indeed a
solution, but it is not straightforward (if the profile is for a role, the
aws configure has to be done against the underlying user profile, not the
profile chosen by the user).
But yes, the hint can be indeed valuable.

**Comment by coderazzi** [comment]
Hi, I released a new version on the beta channel (2.2.0-beta) covering this issue. Could you give it a try?

**Comment by raman-blyshchyk-vib** [comment]
Sure, no problem, but for now last beta I see on plugins page https://plugins.jetbrains.com/plugin/16777-aws-codeartifact--maven/versions/beta is 2.1.1-beta

**Comment by coderazzi** [comment]
Yah, JetBrains it is still approving it, tomorrow should be visible.

**Comment by raman-blyshchyk-vib** [comment]
Tested, works like a charm. One small detail, in message "aws configure --profile myProfileName " there is extra space after profile name. I checked that my profile names don't contain any extra whitespaces after.

**Comment by coderazzi** [comment]
Thanks for your time, Raman, I have removed that trailing space and
released the plugin as version 2.2.0 on the stable channel.

There is a separate issue concerning regions (
https://github.com/coderazzi/aws_codeartifact_maven/issues/7), I will
implement it in the following days.
